# =>what is programming?
# ->programming is a way to instruct the computer to perform various tasks.

# =>what is python?
# ->python is a high level, dynamically typed, object oriented programming language which is simple and easy to understand and is used for communicating with the computer.

# =>features of Python
# ->portable
# ->easy to understand which means less development Time
# ->free and opensource
# ->high level language
# ->dynamically typed language

# =>what is pip?
# ->pip is the __package__ manager for python. pip is used to install any module on the system.
# pip install flask   ......and it will install the flask module.

# =>what is module?
# ->module is a file containing code written by somebody else (usually) which can be imported and used in  our program.
# There are two types of modules in the python:-
# 1.built in modules(pre-installed in python)
# examples of some built in modules are os, random etc.
# 2.external modules(needs to be installed using pip)
# examples of some external modules are tensorflow, flask etc.

# =>comments
# ->comments are something which is written inside the code which the programmer doesnot want to execute.

#----------------------------------------------------------------------------------

# import pyjokes

# # This is a random joke

# joke = pyjokes.get_joke()

# print(joke)

# """
# multi line comment
# """


# print("Hello World")
# name ="anurag"
# print(len(name)) 


# def goodDay(name,ending):
#     print("goodmorning ,"+name)
#     print(ending)
#     return "done"
# a=goodDay("harry","bye bye")
# print(a)


# class employee:
#     company="youtube"
# harry=employee()
# print(harry.company)
# employee.company="google"
# print(harry.company)


# a = 4<=5
# print(a)


# b = True or False
# print(b)
# c = True and False
# print(c)
# print(not(True))


# marks={
#     0 : "harry",
#     "reena" : 90,
#     "pinky" : 78
# }
# print(marks.get(0))
# marks.update({0 : "jeenu", 9 : "bhanumati"})
# print(marks)


# l = [2,2,6,4]
# l.sort()
# print(l)

# t=(1,2,3,3,4)
# print(t.count(3))
# print(t[1:4])









